name: Test

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - reopened
    - synchronize

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      run: |
        curl -L https://unpkg.com/@pnpm/self-installer | node
        pnpm config set store-dir ~/.pnpm-store
        pnpm i --frozen-lockfile --no-verify-store-integrity
    - name: Test
      run: |
        pnpm test
        pnpx vsce package
